import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5522/login');
  await page.getByPlaceholder('Enter your email').click();
  await page.getByPlaceholder('Enter your email').fill('grodriguez@contextglobal.com');
  await page.getByPlaceholder('Enter your email').press('Tab');
  await page.getByPlaceholder('**********').fill('123456');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByText('View quick glance').first().click();
  await page.getByRole('link', { name: 'All events' }).click();
  await page.locator('a').filter({ hasText: 'Devices' }).click();
  await page.locator('#rc_select_1').click();
  await page.getByTitle('checking staff headset empty field').getByText('checking staff headset empty field').click();
  await page.locator('#root').getByTitle('checking staff headset empty field').click();
  await page.getByTitle('National Association of Convenience Stores').getByText('National Association of Convenience Stores').click();
  await page.getByLabel('Status').getByRole('button', { name: 'filter' }).click();
  await page.getByRole('menuitem', { name: 'In Use' }).getByLabel('').check();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByLabel('Serial Number').locator('div').click();
  await page.getByLabel('Serial Number').locator('div').click();
  await page.getByRole('row', { name: 'Receivers Brand Operational In Use 001402' }).getByRole('link').click();
  await page.getByText('jorge.arce@oxxo.com').click();
  await page.getByRole('row', { name: 'pi_x7LewFogemeL 1 Cancel Capture' }).getByRole('button').first().click();
  await page.getByText('National Association of Convenience Stores', { exact: true }).click();
  await page.locator('a').filter({ hasText: 'Consumers' }).click();
  await page.getByPlaceholder('Search', { exact: true }).click();
  await page.getByPlaceholder('Search', { exact: true }).fill('gar.santeliz@gmail.com');
  await page.getByPlaceholder('Search', { exact: true }).press('Enter');
  await page.locator('li').filter({ hasText: 'Gustavo, Rodriguezgar.santeliz@gmail.com, AdministratoradminMore detail' }).getByRole('button').click();
  await page.locator('#responsive-navbar-nav svg').nth(1).click();
  await page.locator('li').filter({ hasText: 'gustavo, rodriguez National Retail Conference Event 9/15/2023 Orlando September ' }).getByRole('button').click();
  await page.locator('a').filter({ hasText: 'Staff' }).click();
  await page.getByRole('row', { name: 'info@contextglobal.com' }).locator('a').first().click();
  await page.getByTitle('Editor').click();
  await page.getByTitle('Approver').getByText('Approver').click();
  await page.getByRole('row', { name: 'Approver Approver info@contextglobal.com' }).locator('a').click();
  await page.getByRole('row', { name: 'info@contextglobal.com' }).locator('a').first().click();
  await page.locator('.ant-select-selector').click();
  await page.getByRole('cell', { name: 'Editor' }).getByTitle('Editor').click();
  await page.getByRole('cell', { name: 'Editor' }).getByTitle('Editor').click();
  await page.getByRole('cell', { name: 'Editor' }).getByTitle('Editor').click();
  await page.getByRole('row', { name: 'rgarcia@contextglobal.com' }).getByRole('cell').nth(2).click();
  await page.getByTitle('Approver').getByText('Approver').click();
  await page.getByRole('row', { name: 'Approver Approver info@contextglobal.com' }).locator('a').click();
  await page.locator('a').filter({ hasText: 'Events' }).click();
  await page.getByText('View quick glance').nth(3).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download' }).click();
  const download = await downloadPromise;
  await page.getByRole('link', { name: 'All events' }).click();
  // await expect(page.locator('div').isVisible())
});